### PR TITLE
Create win_go_get.ps1

### PR DESCRIPTION
**Pull request by arosso3**
#2

### CODE REVIEW

**Comment by kastolars** [comment]
Have you tried running this to see if it works? I'm unable to run it in Git Bash on my windows machine, but it might be for machine specific reasons. What's your setup?

**Comment by arosso3** [comment]
What error are you running into?

**Comment by kastolars** [comment]
I'm not able to _run_ it.

**Comment by arosso3** [comment]
Ok, but how is it not running? What happens when you try and run it?

**Comment by kastolars** [comment]
There is no trying lol, it cannot be run. As in I cannot run it. It is simply a file that is not deemed an executable. Have you run it and does it work?

**Comment by arosso3** [comment]
Yeah, it works for me.

**Comment by kastolars** [comment]
Just merge it directly to `master`

**Pull request merged**
